2025-10-26 00:35:34,967 DEBUG    root            Loaded Command Group: ['gcloud', 'artifacts']
2025-10-26 00:35:34,969 DEBUG    root            Loaded Command Group: ['gcloud', 'artifacts', 'print_settings']
2025-10-26 00:35:35,160 DEBUG    root            Loaded Command Group: ['gcloud', 'artifacts', 'print-settings', 'mvn']
2025-10-26 00:35:35,170 DEBUG    root            Running [gcloud.artifacts.print-settings.mvn] with arguments: [--location: "europe-west9", --project: "tidy-hold-475217-m4", --repository: "ms-products"]
2025-10-26 00:35:35,401 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/511536698491-compute@developer.gserviceaccount.com/?recursive=true
2025-10-26 00:35:35,420 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2025-10-26 00:35:35,422 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/511536698491-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 197
2025-10-26 00:35:35,441 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/511536698491-compute@developer.gserviceaccount.com/token
2025-10-26 00:35:35,462 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/511536698491-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 869
2025-10-26 00:35:35,521 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): artifactregistry.googleapis.com:443
2025-10-26 00:35:35,580 DEBUG    urllib3.connectionpool https://artifactregistry.googleapis.com:443 "GET /v1/projects/tidy-hold-475217-m4/locations/europe-west9/repositories/ms-products?alt=json HTTP/1.1" 403 None
2025-10-26 00:35:35,586 DEBUG    root            Chosen display Format:default
2025-10-26 00:35:35,731 DEBUG    root            Chosen display Format:default
2025-10-26 00:35:35,734 DEBUG    root            Chosen display Format:default
2025-10-26 00:35:35,735 DEBUG    root            (gcloud.artifacts.print-settings.mvn) PERMISSION_DENIED: Request had insufficient authentication scopes. This command is authenticated as 511536698491-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    method: google.devtools.artifactregistry.v1.ArtifactRegistry.GetRepository
    service: artifactregistry.googleapis.com
  reason: ACCESS_TOKEN_SCOPE_INSUFFICIENT

If you are in a compute engine VM, it is likely that the specified scopes during VM creation are not enough to run this command.
See https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam for more information about access scopes.
See https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes for how to update access scopes of the VM.
Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 944, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 955, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/surface/artifacts/print_settings/mvn.py", line 68, in Run
    return {"mvn": settings_util.GetMavenSnippet(args)}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/artifacts/print_settings/settings_util.py", line 237, in GetMavenSnippet
    location, repo_path, maven_cfg = _GetLocationRepoPathAndMavenConfig(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/artifacts/print_settings/settings_util.py", line 96, in _GetLocationRepoPathAndMavenConfig
    repo = ar_requests.GetRepository(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/artifacts/requests.py", line 248, in GetRepository
    get_repo_res = client.projects_locations_repositories.Get(get_repo_req)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/artifactregistry/v1/artifactregistry_v1_client.py", line 1717, in Get
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://artifactregistry.googleapis.com/v1/projects/tidy-hold-475217-m4/locations/europe-west9/repositories/ms-products?alt=json>: response: <{'www-authenticate': 'Bearer realm="https://accounts.google.com/", error="insufficient_scope", scope="https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-platform.read-only"', 'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 26 Oct 2025 00:35:35 GMT', 'server': 'ESF', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.devtools.artifactregistry.v1.ArtifactRegistry.GetRepository",
          "service": "artifactregistry.googleapis.com"
        }
      }
    ]
  }
}
>
2025-10-26 00:35:35,790 ERROR    root            (gcloud.artifacts.print-settings.mvn) PERMISSION_DENIED: Request had insufficient authentication scopes. This command is authenticated as 511536698491-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    method: google.devtools.artifactregistry.v1.ArtifactRegistry.GetRepository
    service: artifactregistry.googleapis.com
  reason: ACCESS_TOKEN_SCOPE_INSUFFICIENT

If you are in a compute engine VM, it is likely that the specified scopes during VM creation are not enough to run this command.
See https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam for more information about access scopes.
See https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes for how to update access scopes of the VM.
